# Generated by Django 3.2.4 on 2021-08-31 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0003_profile_reset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=10000)),
                ('description', models.CharField(blank=True, default='', max_length=1000000)),
                ('place_name', models.CharField(blank=True, default='', max_length=1000000)),
                ('longitude', models.CharField(blank=True, default='', max_length=10000)),
                ('latitude', models.CharField(blank=True, default='', max_length=10000)),
                ('event_date', models.CharField(blank=True, default='', max_length=10000)),
                ('date_object', models.DateField(blank=True)),
                ('enrolled', models.ManyToManyField(related_name='Enrolled_People', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
