# Generated by Django 3.2.4 on 2021-08-31 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0004_initiative_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative_table',
            name='enrolled',
            field=models.ManyToManyField(related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
